; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custo\m upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:stm32]
platform = ststm32
board = nucleo_g474re
framework = arduino
upload_speed = 460800
monitor_speed = 115200
upload_protocol = stlink
debug_tool = stlink
; Sobrescreve as especificações para o chip exato RCT6
board_build.mcu = stm32g474rct6
board_build.f_cpu = 170000000L
; Redefine o tamanho máximo de memória flash (256 KB para o RCT6)
board_upload.maximum_size = 262144
; CLang formatter config
check_tool = clangtidy
check_flags =
  clangtidy: --config-file=.clang-tidy

  extra_scripts = post:fix_ar.py
build_flags =
  -DENABLE_HWSERIAL1
  -DPIN_SERIAL1_RX=PA10
  -DPIN_SERIAL1_TX=PA9

[env:desktop] ; For unit tests
platform = native
build_flags = -D unitTesting
build_type = test
test_build_src = yes
build_src_filter = +<*> -<main.cpp> -<drivers/>